# .eas/workflows/build.yaml
name: Multi-Target Android Build

on:
  push:
    branches: ["main"]

jobs:
  play-store-build:
    name: Build for Google Play Store
    type: build
    params:
      platform: android
      profile: production

  solana-build:
    name: Build for Solana App Store
    type: build
    params:
      platform: android
      profile: solana
